
{*******************************************************}
{                                                       }
{       Borland Delphi Runtime Library                  }
{                                                       }
{       Copyright (c) 1997,99 Inprise Corporation       }
{                                                       }
{*******************************************************}

unit jconsts;

interface

resourcestring
  sChangeJPGSize = 'Cannot change the size of a JPEG image';
  sJPEGError = 'JPEG error #%d';
  sJPEGImageFile = 'JPEG Image File';
  
implementation

end.
 